name: 'RSS diff to Twitter'
description: 'GitHub Action to tweet the newly added items in an RSS feed'
author: 'utelecon'
branding:
  icon: 'rss'
  color: 'blue'

inputs:
  OLD_RSS:
    description: Path to the old RSS file
    required: true
  NEW_RSS:
    description: Path to the new RSS file
    required: true
  TWITTER_APIKEY:
    description: Twitter API Key (App Key)
    required: true
  TWITTER_APIKEY_SECRET:
    description: Twitter API Secret (App key secret)
    required: true
  TWITTER_ACCESS_TOKEN:
    description: Twitter Access Token
    required: true
  TWITTER_ACCESS_TOKEN_SECRET:
    description: Twitter Access Token Secret
    required: true
  POST_LIMIT:
    description: |
      Maximum number of posts to tweet.
      If the number of new posts exceeds this value, the action will fail and no tweets will be sent.
      When this value is negative, all new posts will be tweeted.
    required: false
    default: -1
  DRY_RUN:
    description: If true, the action will not tweet anything.
    required: false
    default: false
runs:
  using: node20
  main: 'dist/index.js'
